-- MySQL Script generated by MySQL Workbench
-- Sun May 28 15:59:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `ad` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `soyad` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `tel` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `dogumTarihi` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_turkish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`doktor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doktor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ad` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `soyad` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `dogumTarihi` DATE NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NULL DEFAULT NULL,
  `tel` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_turkish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`doktor_bilgi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doktor_bilgi` (
  `doktor_id` INT(11) NOT NULL,
  `bilgi` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  PRIMARY KEY (`doktor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_turkish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`iletisim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`iletisim` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ad` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NULL DEFAULT NULL,
  `mesaj` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_turkish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`kullanicigiris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kullanicigiris` (
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `sifre` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `yetki_id` INT(11) NOT NULL,
  `resim` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_turkish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`musteri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`musteri` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `musteriAd` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `musteriSoyad` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NULL DEFAULT NULL,
  `tel` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  `mesaj` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NULL DEFAULT NULL,
  `randevuTarihi` DATE NOT NULL,
  `saat_id` INT(11) NOT NULL,
  `doktor_id` INT(11) NULL DEFAULT NULL,
  `randevuOnay` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_turkish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`musteri_detay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`musteri_detay` (
  `detay_id` INT(11) NOT NULL AUTO_INCREMENT,
  `musteri_id` INT(11) NULL DEFAULT NULL,
  `randevu_tarihi` DATE NULL DEFAULT NULL,
  `saat_id` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NULL DEFAULT NULL,
  `doktor_id` INT(11) NULL DEFAULT NULL,
  `yapilan_islem` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NULL DEFAULT NULL,
  `yapilacak_islem` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NULL DEFAULT NULL,
  `muayneDurumu` INT(255) NULL DEFAULT NULL,
  PRIMARY KEY (`detay_id`),
  INDEX `fk_musteri_id` (`musteri_id` ASC),
  CONSTRAINT `fk_musteri_id`
    FOREIGN KEY (`musteri_id`)
    REFERENCES `mydb`.`musteri` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_turkish_ci;


-- -----------------------------------------------------
-- Table `mydb`.`saat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saat` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `saatAdi` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_turkish_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_turkish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
